#ifndef _BLE_SERVICE_H_
#define _BLE_SERVICE_H_

/* Handle Index */
#define BLE_UART_NOTIFY_IDX 0
#define BLE_Battry_Level_IDX 1
#define BLE_WECHAT_Indication_IDX 2

/* GENERIC_ACCESS*/
#define BLE_GENERIC_ACCESS 0x1800
#define BLE_DEVICE_NAME_UUID 0x2A00
#define BLE_DEVICE_NAME_VALUE_HANDLE 0x0003
#define BLE_APPEARANCE_UUID 0x2A01
#define BLE_APPEARANCE_VALUE_HANDLE 0x0005
#define BLE_Peripheral_Preferred_Connection_Parameters_UUID 0x2A04
#define BLE_Peripheral_Preferred_Connection_Parameters_VALUE_HANDLE 0x0007

/* Generic_Attribute*/
#define BLE_Generic_Attribute 0x1801
#define BLE_Service_Changed_UUID 0x2A05
#define BLE_Service_Changed_VALUE_HANDLE 0x000A

/* Device_Information*/
#define BLE_Device_Information 0x180A
#define BLE_MANUFACTURER_NAME_STRING_UUID 0x2A29
#define BLE_MANUFACTURER_NAME_STRING_VALUE_HANDLE 0x000E
#define BLE_MODEL_NUMBER_STRING_UUID 0x2A24
#define BLE_MODEL_NUMBER_STRING_VALUE_HANDLE 0x0010
#define BLE_SERIAL_NUMBER_STRING_UUID 0x2A25
#define BLE_SERIAL_NUMBER_STRING_VALUE_HANDLE 0x0012
#define BLE_HARDWARE_REVISION_STRING_UUID 0x2A27
#define BLE_HARDWARE_REVISION_STRING_VALUE_HANDLE 0x0014
#define BLE_FIRMWARE_REVISION_STRING_UUID 0x2A26
#define BLE_FIRMWARE_REVISION_STRING_VALUE_HANDLE 0x0016
#define BLE_SOFTWARE_REVISION_STRING_UUID 0x2A28
#define BLE_SOFTWARE_REVISION_STRING_VALUE_HANDLE 0x0018
#define BLE_PNP_ID_UUID 0x2A50
#define BLE_PNP_ID_VALUE_HANDLE 0x001A

/* UART*/
#define BLE_UART 0x0001
#define BLE_UART_Write_UUID 0x0002
#define BLE_UART_Write_VALUE_HANDLE 0x001D
#define BLE_UART_NOTIFY_UUID 0x0003
#define BLE_UART_NOTIFY_VALUE_HANDLE 0x001F

/* OTA*/
#define BLE_OTA 0xFF00
#define BLE_OTA_Read_Write_UUID 0xFF01
#define BLE_OTA_Read_Write_VALUE_HANDLE 0x0023

/* BATTERY_SERVICE*/
#define BLE_BATTERY_SERVICE 0x180F
#define BLE_Battry_Level_UUID 0x2A19
#define BLE_Battry_Level_VALUE_HANDLE 0x0026

/* WECHAT*/
#define BLE_WECHAT 0xfee7
#define BLE_WECHAT_WRITE_UUID 0xFEC7
#define BLE_WECHAT_WRITE_VALUE_HANDLE 0x002A
#define BLE_WECHAT_Indication_UUID 0xFEC8
#define BLE_WECHAT_Indication_VALUE_HANDLE 0x002C
#define BLE_WECHAT_Read_UUID 0xFEC9
#define BLE_WECHAT_Read_VALUE_HANDLE 0x002F

#endif
