#ifndef _BLE_SERVICE_H_
#define _BLE_SERVICE_H_

/* Handle Index */
#define BLE_UART_NOTIFY_IDX 0
#define BLE_Battry_Level_IDX 1
#define BLE_BOOT_KEY_REPORT_IDX 2
#define BLE_BOOT_MOUSE_REPORT_IDX 3
#define BLE_Consumer_REPORT_IDX 4
#define BLE_BOOT_KEYBOARD_INPUT_REPORT_IDX 5
#define BLE_BOOT_MOUSE_INPUT_REPORT_IDX 6

/* GENERIC_ACCESS*/
#define BLE_GENERIC_ACCESS 0x1800
#define BLE_DEVICE_NAME_UUID 0x2A00
#define BLE_DEVICE_NAME_VALUE_HANDLE 0x0003
#define BLE_APPEARANCE_UUID 0x2A01
#define BLE_APPEARANCE_VALUE_HANDLE 0x0005
#define BLE_Peripheral_Preferred_Connection_Parameters_UUID 0x2A04
#define BLE_Peripheral_Preferred_Connection_Parameters_VALUE_HANDLE 0x0007

/* UART*/
#define BLE_UART 0x0001
#define BLE_UART_Write_UUID 0x0002
#define BLE_UART_Write_VALUE_HANDLE 0x000A
#define BLE_UART_NOTIFY_UUID 0x0003
#define BLE_UART_NOTIFY_VALUE_HANDLE 0x000C

/* OTA*/
#define BLE_OTA 0xFF00
#define BLE_OTA_Read_Write_UUID 0xFF01
#define BLE_OTA_Read_Write_VALUE_HANDLE 0x0010

/* BATTERY_SERVICE*/
#define BLE_BATTERY_SERVICE 0x180F
#define BLE_Battry_Level_UUID 0x2A19
#define BLE_Battry_Level_VALUE_HANDLE 0x0013

/* HIDO_SERVICE*/
#define BLE_HIDO_SERVICE 0x1812
#define BLE_PROTOCOL_MODE_UUID 0x2A4E
#define BLE_PROTOCOL_MODE_VALUE_HANDLE 0x0017
#define BLE_BOOT_KEY_REPORT_UUID 0x2A4D
#define BLE_BOOT_KEY_REPORT_VALUE_HANDLE 0x0019
#define BLE_BOOT_MOUSE_REPORT_UUID 0x2A4D
#define BLE_BOOT_MOUSE_REPORT_VALUE_HANDLE 0x001D
#define BLE_Consumer_REPORT_UUID 0x2A4D
#define BLE_Consumer_REPORT_VALUE_HANDLE 0x0021
#define BLE_KEYBOARD_OUTPUT_REPORT_UUID 0x2A4D
#define BLE_KEYBOARD_OUTPUT_REPORT_VALUE_HANDLE 0x0025
#define BLE_REPORT_MAP_UUID 0x2A4B
#define BLE_REPORT_MAP_VALUE_HANDLE 0x0028
#define BLE_BOOT_KEYBOARD_INPUT_REPORT_UUID 0x2A22
#define BLE_BOOT_KEYBOARD_INPUT_REPORT_VALUE_HANDLE 0x002A
#define BLE_BOOT_KEYBOARD_OUTPUT_REPORT_UUID 0x2A32
#define BLE_BOOT_KEYBOARD_OUTPUT_REPORT_VALUE_HANDLE 0x002D
#define BLE_BOOT_MOUSE_INPUT_REPORT_UUID 0x2A33
#define BLE_BOOT_MOUSE_INPUT_REPORT_VALUE_HANDLE 0x002F
#define BLE_HID_INFORMATION_UUID 0x2A4A
#define BLE_HID_INFORMATION_VALUE_HANDLE 0x0032
#define BLE_HID_CONTROL_POINT_UUID 0x2A4C
#define BLE_HID_CONTROL_POINT_VALUE_HANDLE 0x0034

#endif
