#ifndef _BLE_SERVICE_H_
#define _BLE_SERVICE_H_

/* Handle Index */
#define BLE_BLOOD_PRESSURE_MEASUREMENT_IDX 0
#define BLE_INTERMEDIATE_CUFF_PRESSURE_IDX 1
#define BLE_Battry_Level_IDX 2

/* GENERIC_ACCESS*/
#define BLE_GENERIC_ACCESS 0x1800
#define BLE_DEVICE_NAME_UUID 0x2A00
#define BLE_DEVICE_NAME_VALUE_HANDLE 0x0003
#define BLE_APPEARANCE_UUID 0x2A01
#define BLE_APPEARANCE_VALUE_HANDLE 0x0005
#define BLE_Peripheral_Preferred_Connection_Parameters_UUID 0x2A04
#define BLE_Peripheral_Preferred_Connection_Parameters_VALUE_HANDLE 0x0007

/* Generic_Attribute*/
#define BLE_Generic_Attribute 0x1801
#define BLE_Service_Changed_UUID 0x2A05
#define BLE_Service_Changed_VALUE_HANDLE 0x000A

/* Device_Information*/
#define BLE_Device_Information 0x180A
#define BLE_MANUFACTURER_NAME_STRING_UUID 0x2A29
#define BLE_MANUFACTURER_NAME_STRING_VALUE_HANDLE 0x000E
#define BLE_MODEL_NUMBER_STRING_UUID 0x2A24
#define BLE_MODEL_NUMBER_STRING_VALUE_HANDLE 0x0010
#define BLE_SERIAL_NUMBER_STRING_UUID 0x2A25
#define BLE_SERIAL_NUMBER_STRING_VALUE_HANDLE 0x0012
#define BLE_HARDWARE_REVISION_STRING_UUID 0x2A27
#define BLE_HARDWARE_REVISION_STRING_VALUE_HANDLE 0x0014
#define BLE_FIRMWARE_REVISION_STRING_UUID 0x2A26
#define BLE_FIRMWARE_REVISION_STRING_VALUE_HANDLE 0x0016
#define BLE_SOFTWARE_REVISION_STRING_UUID 0x2A28
#define BLE_SOFTWARE_REVISION_STRING_VALUE_HANDLE 0x0018
#define BLE_PNP_ID_UUID 0x2A50
#define BLE_PNP_ID_VALUE_HANDLE 0x001A
#define BLE_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_UUID 0x2A2A
#define BLE_IEEE_11073_20601_REGULATORY_CERTIFICATION_DATA_LIST_VALUE_HANDLE 0x001C
#define BLE_SCAN_REFRESH_UUID 0x2A31
#define BLE_SCAN_REFRESH_VALUE_HANDLE 0x001E
#define BLE_SYSTEM_ID_UUID 0x2A23
#define BLE_SYSTEM_ID_VALUE_HANDLE 0x0020
#define BLE_Unknown_Characteristic_UUID 0x2A30
#define BLE_Unknown_Characteristic_VALUE_HANDLE 0x0022

/* BLOOD_PRESSURE*/
#define BLE_BLOOD_PRESSURE 0x1810
#define BLE_BLOOD_PRESSURE_MEASUREMENT_UUID 0x2A35
#define BLE_BLOOD_PRESSURE_MEASUREMENT_VALUE_HANDLE 0x0025
#define BLE_INTERMEDIATE_CUFF_PRESSURE_UUID 0x2A36
#define BLE_INTERMEDIATE_CUFF_PRESSURE_VALUE_HANDLE 0x0028
#define BLE_BLOOD_PRESSURE_FEATURE_UUID 0x2A49
#define BLE_BLOOD_PRESSURE_FEATURE_VALUE_HANDLE 0x002B

/* OTA*/
#define BLE_OTA 0xFF00
#define BLE_OTA_Read_Write_UUID 0xFF01
#define BLE_OTA_Read_Write_VALUE_HANDLE 0x002E

/* BATTERY_SERVICE*/
#define BLE_BATTERY_SERVICE 0x180F
#define BLE_Battry_Level_UUID 0x2A19
#define BLE_Battry_Level_VALUE_HANDLE 0x0031

#endif
