#ifndef _BLE_SERVICE_H_
#define _BLE_SERVICE_H_

/* Handle Index */
#define BLE_SERVICE_CHANGED_IDX 0
#define BLE_UART_NOTIFY_IDX 1
#define BLE_Battry_Level_IDX 2
#define BLE_BOOT_KEY_REPORT_IDX 3
#define BLE_BOOT_MOUSE_REPORT_IDX 4
#define BLE_Consumer_REPORT_IDX 5
#define BLE_BOOT_KEYBOARD_INPUT_REPORT_IDX 6
#define BLE_BOOT_MOUSE_INPUT_REPORT_IDX 7

/* GENERIC_ACCESS*/
#define BLE_GENERIC_ACCESS 0x1800
#define BLE_DEVICE_NAME_UUID 0x2A00
#define BLE_DEVICE_NAME_VALUE_HANDLE 0x0003
#define BLE_APPEARANCE_UUID 0x2A01
#define BLE_APPEARANCE_VALUE_HANDLE 0x0005
#define BLE_Peripheral_Preferred_Connection_Parameters_UUID 0x2A04
#define BLE_Peripheral_Preferred_Connection_Parameters_VALUE_HANDLE 0x0007

/* GENERIC_ATTRIBUTE*/
#define BLE_GENERIC_ATTRIBUTE 0x1801
#define BLE_SERVICE_CHANGED_UUID 0x2A05
#define BLE_SERVICE_CHANGED_VALUE_HANDLE 0x000A

/* UART*/
#define BLE_UART 0x0001
#define BLE_UART_Write_UUID 0x0002
#define BLE_UART_Write_VALUE_HANDLE 0x000E
#define BLE_UART_NOTIFY_UUID 0x0003
#define BLE_UART_NOTIFY_VALUE_HANDLE 0x0010

/* OTA*/
#define BLE_OTA 0xFF00
#define BLE_OTA_Read_Write_UUID 0xFF01
#define BLE_OTA_Read_Write_VALUE_HANDLE 0x0014

/* BATTERY_SERVICE*/
#define BLE_BATTERY_SERVICE 0x180F
#define BLE_Battry_Level_UUID 0x2A19
#define BLE_Battry_Level_VALUE_HANDLE 0x0017

/* HIDO_SERVICE*/
#define BLE_HIDO_SERVICE 0x1812
#define BLE_PROTOCOL_MODE_UUID 0x2A4E
#define BLE_PROTOCOL_MODE_VALUE_HANDLE 0x001B
#define BLE_BOOT_KEY_REPORT_UUID 0x2A4D
#define BLE_BOOT_KEY_REPORT_VALUE_HANDLE 0x001D
#define BLE_BOOT_MOUSE_REPORT_UUID 0x2A4D
#define BLE_BOOT_MOUSE_REPORT_VALUE_HANDLE 0x0021
#define BLE_Consumer_REPORT_UUID 0x2A4D
#define BLE_Consumer_REPORT_VALUE_HANDLE 0x0025
#define BLE_KEYBOARD_OUTPUT_REPORT_UUID 0x2A4D
#define BLE_KEYBOARD_OUTPUT_REPORT_VALUE_HANDLE 0x0029
#define BLE_REPORT_MAP_UUID 0x2A4B
#define BLE_REPORT_MAP_VALUE_HANDLE 0x002C
#define BLE_BOOT_KEYBOARD_INPUT_REPORT_UUID 0x2A22
#define BLE_BOOT_KEYBOARD_INPUT_REPORT_VALUE_HANDLE 0x002E
#define BLE_BOOT_KEYBOARD_OUTPUT_REPORT_UUID 0x2A32
#define BLE_BOOT_KEYBOARD_OUTPUT_REPORT_VALUE_HANDLE 0x0031
#define BLE_BOOT_MOUSE_INPUT_REPORT_UUID 0x2A33
#define BLE_BOOT_MOUSE_INPUT_REPORT_VALUE_HANDLE 0x0033
#define BLE_HID_INFORMATION_UUID 0x2A4A
#define BLE_HID_INFORMATION_VALUE_HANDLE 0x0036
#define BLE_HID_CONTROL_POINT_UUID 0x2A4C
#define BLE_HID_CONTROL_POINT_VALUE_HANDLE 0x0038

#endif
